/**
 * Centralized business configuration.
 *
 * Every component that needs the shop's name, address, hours, or contact
 * details must import it from here — never re-type or hardcode this
 * information inside a page or component. When the owner's real details
 * change, this is the only file that needs editing.
 *
 * Deliberately kept as static code even after Phase 8 added a real
 * Firestore backend for products/offers/gallery: this data changes far
 * less often than a catalog, and moving it to Firestore would add a
 * database round-trip to every page for no real benefit. If that
 * tradeoff ever changes, this can be swapped for a `settings/business`
 * Firestore doc (see firestore.rules, which already reserves that path
 * for admin-only writes) without changing any component that consumes it,
 * as long as the shape below is preserved.
 */

export const business = {
  name: 'MeShape Gift Shop',

  address: {
    line1: 'Vandavasi–Acharapakkam Road, 1st Floor',
    city: '',
    state: 'Tamil Nadu',
    // Full display string for places that just need one line of text.
    full: 'Vandavasi–Acharapakkam Road, 1st Floor, Tamil Nadu',
  },

  hours: {
    open: '09:00',
    close: '22:00',
    displayText: '9:00 AM – 10:00 PM',
    weeklyHoliday: null, // no weekly holiday
    weeklyHolidayText: 'No weekly holiday',
  },

  delivery: {
    coverageText: 'Delivery all over India',
    // Deliberately no numeric fee here — see src/config/delivery.js
  },

  contact: {
    orderWhatsapp: '+91 93607 62534',
    // Digits-only version for wa.me links (no +, spaces, or dashes).
    orderWhatsappDigits: '919360762534',
    shopPhone: '+91 93607 62534',
    // Fix (BUG-23): tel: links rendered as tel:919360762534 with no
    // international prefix. Most Indian handsets cope, but the '+' is
    // what makes the number unambiguous from any network or country,
    // and it matches how the number is displayed on the page.
    shopPhoneDigits: '+919360762534',
  },

  social: {
    instagram: 'https://www.instagram.com/vandavasi_meshape_gift_shop?stkn=emwzY2h2MzM3eDU3',
  },

  maps: {
    // Use this exact link everywhere — do not regenerate or shorten differently.
    googleMapsUrl: 'https://maps.app.goo.gl/PQnoberjSGxEmaVq5?g_st=aw',
  },
};

/**
 * Developer / agency brand. Kept separate from `business` so it is obvious
 * in code review that these two identities are never meant to merge.
 */
export const agency = {
  name: 'Craft Tech',
  tagline: 'Craft Tech — Turning Ideas into Digital Solutions',
  // The logo file itself is not generated by this codebase — see
  // src/assets/branding/README.md for exactly where to place the
  // client-approved logo asset.
  //
  // Optional link for the footer credit. Left empty because there is no
  // agency URL to point at yet — Footer.jsx renders the credit as plain
  // text rather than a dead link while this is empty (BUG-14).
  url: '',

  // Bug fix (Phase 10 QA): this previously pointed at
  // /src/assets/branding/craft-tech-logo.svg, which only resolves during
  // `npm run dev` (Vite's dev server serves the whole project root) — a
  // production `vite build` never copies arbitrary files out of src/
  // into dist/, only explicitly `import`-ed assets or anything placed in
  // public/. Anything referenced as a raw URL string like this must live
  // in public/ instead.
  //
  // Fix (BUG-15): it then pointed at /craft-tech-logo.svg, which was
  // never added to public/ either — so every page load fired a request
  // that 404'd, hidden by Footer.jsx's onError fallback. Null until the
  // client's approved asset actually exists: drop the file into public/
  // and set this to '/craft-tech-logo.svg' to switch the logo on.
  logoPath: null,
};

export default business;
